name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Sync with S3
        uses: sai-sharan/aws-s3-sync-action@master
        with:
          access_key: ${{ secrets.AWS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: 'sa-east-1'
          source: '_site'
          destination_bucket: ${{ secrets.TF_VAR_S3_BUCKET }}
          destination_prefix: ''
          exclude: '.git/*'
          delete: true
          quiet: false

      # - name: Upload to S3
      #   uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_bucket: ${{ secrets.TF_VAR_S3_BUCKET }}
      #     source_dir: '_site'
      #     destination_dir: ''

      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: '/'
          AWS_REGION: 'sa-east-1'
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}